database:
  default: main
  connections:
    main:
      driver: gormdriver
      engine: sqlite
      database: example.db
      max_idle_conns: 5
      max_open_conns: 20
      conn_max_lifetime: 60
      conn_max_idle_time: 30

http:
  driver: fiber
  host: 0.0.0.0
  port: 8000

log:
  level: debug
  mode: console
